# Generated by Django 5.2.3 on 2025-06-19 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('contact', models.CharField()),
                ('qualification', models.CharField()),
                ('gender', models.CharField()),
                ('password', models.CharField()),
                ('image', models.ImageField(upload_to='image/')),
                ('file', models.FileField(upload_to='file/')),
                ('discription', models.CharField()),
            ],
        ),
    ]
