# Generated by Django 5.2.3 on 2025-06-19 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='discription',
            new_name='dob',
        ),
        migrations.RenameField(
            model_name='student',
            old_name='qualification',
            new_name='education',
        ),
        migrations.AlterField(
            model_name='student',
            name='file',
            field=models.FileField(upload_to='files/'),
        ),
        migrations.AlterField(
            model_name='student',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
