# Generated by Django 5.2.3 on 2025-06-19 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_discription_student_dob_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='discription',
            field=models.CharField(null=True),
        ),
    ]
