# Generated by Django 5.2.3 on 2025-06-22 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_student_discription'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='confirmpass',
            field=models.CharField(null=True),
        ),
    ]
