# Generated by Django 5.2.3 on 2025-06-22 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_student_confirmpass'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='confirmpass',
        ),
    ]
